/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package QKART_SANITY_LOGIN.Module1;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Set;
import java.util.concurrent.TimeUnit;

import org.apache.commons.io.FileUtils;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.WindowType;
import org.openqa.selenium.remote.BrowserType;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Wait;
import org.openqa.selenium.support.ui.WebDriverWait;

public class QkartSanity {

    public static String lastGeneratedUserName;


    public static RemoteWebDriver createDriver() throws MalformedURLException {
        // Launch Browser using Zalenium
        final DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setBrowserName(BrowserType.CHROME);
        RemoteWebDriver driver = new RemoteWebDriver(new URL("http://localhost:8082/wd/hub"), capabilities);

        return driver;
    }

    public static void logStatus(String type, String message, String status) {

        System.out.println(String.format("%s |  %s  |  %s | %s", String.valueOf(java.time.LocalDateTime.now()), type,
                message, status));
    }

    public static void takeScreenshot(WebDriver driver, String screenshotType, String description) {
        

        try {
			File theDir = new File("/screenshots");
			if (!theDir.exists()) {
				theDir.mkdirs();
			}

			String timestamp = String.valueOf(java.time.LocalDateTime.now());
			String fileName = String.format("screenshot_%s_%s_%s.png", timestamp, screenshotType, description);

			TakesScreenshot scrShot = ((TakesScreenshot) driver);
			File SrcFile = scrShot.getScreenshotAs(OutputType.FILE);

			File DestFile = new File("screenshots/" + fileName);
			FileUtils.copyFile(SrcFile, DestFile);
		} catch (Exception e) {
			e.printStackTrace();
		}
    }

    /*
     * Testcase01: Verify the functionality of Login button on the Home page
     */
    public static Boolean TestCase01(RemoteWebDriver driver) throws InterruptedException {
        takeScreenshot(driver, "StartTestcase", "Testcase01");
        Boolean status;
        logStatus("Start TestCase", "Test Case 1: Verify User Registration", "DONE");

        // Visit the Registration page and register a new user
        Register registration = new Register(driver);
        registration.navigateToRegisterPage();
        status = registration.registerUser("testUser", "abc@123", true);
        if (!status) {
            logStatus("End TestCase", "Test Case 1: Verify user Registration : ", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase01");

            // Return False as the test case Fails
            return false;
        } else {
            logStatus("TestCase 1", "Test Case Pass. User Registration Pass", "PASS");
        }

        // Save the last generated username
        lastGeneratedUserName = registration.lastGeneratedUsername;

        // Visit the login page and login with the previuosly registered user
        Login login = new Login(driver);
        login.navigateToLoginPage();
        status = login.PerformLogin(lastGeneratedUserName, "abc@123");
        logStatus("Test Step", "User Perform Login: ", status ? "PASS" : "FAIL");
        if (!status) {
            logStatus("End TestCase", "Test Case 1: Verify user Registration : ", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase01");
            return false;
        }

        // Visit the home page and log out the logged in user
        Home home = new Home(driver);
        status = home.PerformLogout();
        logStatus("End TestCase", "Test Case 1: Verify user Registration : ", status ? "PASS" : "FAIL");

        takeScreenshot(driver, "EndTestcase", "Testcase01");
        return status;
    }

    /*
     * Verify that an existing user is not allowed to re-register on QKart
     */
    public static Boolean TestCase02(RemoteWebDriver driver) throws InterruptedException {
        takeScreenshot(driver, "StartTestcase", "Testcase02");
        Boolean status;
        logStatus("Start Testcase", "Test Case 2: Verify User Registration with an existing username ", "DONE");

        // Visit the Registration page and register a new user
        Register registration = new Register(driver);
        registration.navigateToRegisterPage();
        status = registration.registerUser("testUser", "abc@123", true);
        logStatus("Test Step", "User Registration : ", status ? "PASS" : "FAIL");
        if (!status) {
            logStatus("End TestCase", "Test Case 2: Verify user Registration : ", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase02");
            return false;

        }

        // Save the last generated username
        lastGeneratedUserName = registration.lastGeneratedUsername;

        // Visit the Registration page and try to register using the previously
        // registered user's credentials
        registration.navigateToRegisterPage();
        status = registration.registerUser(lastGeneratedUserName, "abc@123", false);

        // If status is true, then registration succeeded, else registration has
        // failed. In this case registration failure means Success
        logStatus("End TestCase", "Test Case 2: Verify user Registration : ", status ? "FAIL" : "PASS");
        takeScreenshot(driver, "EndTestcase", "Testcase02");
        return !status;
    }

    /*
     * Verify the functinality of the search text box
     */
    public static Boolean TestCase03(RemoteWebDriver driver) throws InterruptedException {
        takeScreenshot(driver, "StartTestcase", "Testcase03");
        logStatus("TestCase 3", "Start test case : Verify functionality of search box ", "DONE");
        boolean status;

        // Visit the home page
        Home homePage = new Home(driver);
        homePage.navigateToHome();

        // Search for the "yonex" product
        status = homePage.searchForProduct("yonex");
        if (!status) {
            logStatus("TestCase 3", "Test Case Failure. Unable to search for given product", "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase03");
            return false;
        }

        // Fetch the search results
        List<WebElement> searchResults = homePage.getSearchResults();

        // Verify the search results are available
        if (searchResults.size() == 0) {
            logStatus("TestCase 3", "Test Case Failure. There were no results for the given search string", "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase03");
            return false;
        }

        for (WebElement webElement : searchResults) {
            // Create a SearchResult object from the parent element
            SearchResult resultelement = new SearchResult(webElement);

            // Verify that all results contain the searched text
            String elementText = resultelement.getTitleofResult();
            if (!elementText.toUpperCase().contains("YONEX")) {
                logStatus("TestCase 3", "Test Case Failure. Test Results contains un-expected values: " + elementText,
                        "FAIL");
                takeScreenshot(driver, "TestcaseFailure", "Testcase03");
                return false;
            }
        }

        logStatus("Step Success", "Successfully validated the search results ", "PASS");

        // Search for product
        status = homePage.searchForProduct("Gesundheit");
        if (!status) {
            logStatus("TestCase 3", "Test Case Failure. Unable to search for given product", "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase03");
            return false;
        }

        // Verify no search results are found
        searchResults = homePage.getSearchResults();
        if (searchResults.size() == 0) {
            if (homePage.isNoResultFound()) {
                logStatus("Step Success", "Successfully validated that no products found message is displayed", "PASS");
            }
            logStatus("TestCase 3", "Test Case PASS. Verified that no search results were found for the given text",
                    "PASS");
        } else {
            takeScreenshot(driver, "TestcaseFailure", "Testcase03");
            logStatus("TestCase 3", "Test Case Fail. Expected: no results , actual: Results were available", "FAIL");
            return false;
        }
        takeScreenshot(driver, "EndTestcase", "Testcase03");
        return true;
    }

    /*
     * Verify the presence of size chart and check if the size chart content is as
     * expected
     */
    public static Boolean TestCase04(RemoteWebDriver driver) throws InterruptedException {
        takeScreenshot(driver, "StartTestcase", "Testcase04");
        logStatus("TestCase 4", "Start test case : Verify the presence of size Chart", "DONE");
        boolean status = false;

        // Visit home page
        Home homePage = new Home(driver);
        homePage.navigateToHome();


        // Search for product and get card content element of search results
        status = homePage.searchForProduct("Running Shoes");
        List<WebElement> searchResults = homePage.getSearchResults();

        // Create expected values
        List<String> expectedTableHeaders = Arrays.asList("Size", "UK/INDIA", "EU", "HEEL TO TOE");
        List<List<String>> expectedTableBody = Arrays.asList(Arrays.asList("6", "6", "40", "9.8"),
                Arrays.asList("7", "7", "41", "10.2"), Arrays.asList("8", "8", "42", "10.6"),
                Arrays.asList("9", "9", "43", "11"), Arrays.asList("10", "10", "44", "11.5"),
                Arrays.asList("11", "11", "45", "12.2"), Arrays.asList("12", "12", "46", "12.6"));

        // Verify size chart presence and content matching for each search result
        for (WebElement webElement : searchResults) {
            SearchResult result = new SearchResult(webElement);

            // Verify if the size chart exists for the search result
            if (result.verifySizeChartExists()) {
                logStatus("Step Success", "Successfully validated presence of Size Chart Link", "PASS");

                // Verify if size dropdown exists
                status = result.verifyExistenceofSizeDropdown(driver);
                logStatus("Step Success", "Validated presence of drop down", status ? "PASS" : "FAIL");

                // Open the size chart
                if (result.openSizechart()) {
                    // Verify if the size chart contents matches the expected values
                    if (result.validateSizeChartContents(expectedTableHeaders, expectedTableBody, driver)) {
                        logStatus("Step Success", "Successfully validated contents of Size Chart Link", "PASS");
                    } else {
                        takeScreenshot(driver, "TestcaseFailure", "Testcase04");
                        logStatus("Step Failure", "Failure while validating contents of Size Chart Link", "FAIL");
                    }

                    // Close the size chart modal
                    status = result.closeSizeChart(driver);

                } else {
                    takeScreenshot(driver, "TestcaseFailure", "Testcase04");
                    logStatus("TestCase 4", "Test Case Fail. Failure to open Size Chart", "FAIL");
                    return false;
                }

            } else {
                logStatus("TestCase 4", "Test Case Fail. Size Chart Link does not exist", "FAIL");
                takeScreenshot(driver, "TestcaseFailure", "Testcase04");
                return false;
            }
        }
        logStatus("TestCase 4", "Test Case PASS. Validated Size Chart Details", "PASS");

        takeScreenshot(driver, "EndTestcase", "Testcase04");
        return status;
    }

    /*
     * Verify the complete flow of checking out and placing order for products is
     * working correctly
     */
    public static Boolean TestCase05(RemoteWebDriver driver) throws InterruptedException {
        takeScreenshot(driver, "StartTestcase", "Testcase05");
        Boolean status;
        logStatus("Start TestCase", "Test Case 5: Verify Happy Flow of buying products", "DONE");

        // Go to the Register page
        Register registration = new Register(driver);
        registration.navigateToRegisterPage();

        // Register a new user
        status = registration.registerUser("testUser", "abc@123", true);
        if (!status) {
            logStatus("TestCase 5", "Test Case Failure. Happy Flow Test Failed", "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase05");
        }

        // Save the username of the newly registered user
        lastGeneratedUserName = registration.lastGeneratedUsername;

        // Go to the login page
        Login login = new Login(driver);
        login.navigateToLoginPage();

        // Login with the newly registered user's credentials
        status = login.PerformLogin(lastGeneratedUserName, "abc@123");
        if (!status) {
            logStatus("Step Failure", "User Perform Login Failed", status ? "PASS" : "FAIL");
            logStatus("End TestCase", "Test Case 5: Happy Flow Test Failed : ", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase05");
        }

        // Go to the home page
        Home homePage = new Home(driver);
        homePage.navigateToHome();

        // Find required products by searching and add them to the user's cart
        status = homePage.searchForProduct("YONEX");
        homePage.addProductToCart("YONEX Smash Badminton Racquet");
        status = homePage.searchForProduct("Tan");
        homePage.addProductToCart("Tan Leatherette Weekender Duffle");

        // Click on the checkout button
        homePage.clickCheckout();

        // Add a new address on the Checkout page and select it
        Checkout checkoutPage = new Checkout(driver);
        checkoutPage.addNewAddress("Addr line 1 addr Line 2 addr line 3");
        checkoutPage.selectAddress("Addr line 1 addr Line 2 addr line 3");

        // Place the order
        checkoutPage.placeOrder();

        // Check if placing order redirected to the Thansk page
        status = driver.getCurrentUrl().endsWith("/thanks");

        // Go to the home page
        homePage.navigateToHome();

        // Log out the user
        homePage.PerformLogout();

        logStatus("End TestCase", "Test Case 5: Happy Flow Test Completed : ", status ? "PASS" : "FAIL");

        takeScreenshot(driver, "EndTestcase", "Testcase05");
        return status;
    }

    /*
     * Verify the quantity of items in cart can be updated
     */
    public static Boolean TestCase06(RemoteWebDriver driver) throws InterruptedException {
        takeScreenshot(driver, "StartTestcase", "Testcase06");
        Boolean status;
        logStatus("Start TestCase", "Test Case 6: Verify that cart can be edited", "DONE");
        Home homePage = new Home(driver);

        Register registration = new Register(driver);
        registration.navigateToRegisterPage();

        status = registration.registerUser("testUser", "abc@123", true);
        if (!status) {
            logStatus("TestCase 6", "Test Case Failure. Happy Flow Test Failed", "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase06");
        }

        lastGeneratedUserName = registration.lastGeneratedUsername;

        Login login = new Login(driver);
        login.navigateToLoginPage();

        status = login.PerformLogin(lastGeneratedUserName, "abc@123");
        if (!status) {
            logStatus("Step Failure", "User Perform Login Failed", status ? "PASS" : "FAIL");
            logStatus("End TestCase", "Test Case 6: Happy Flow Test Failed : ", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase06");
        }

        homePage.navigateToHome();

        status = homePage.searchForProduct("Xtend");
        if (!status) {
            logStatus("Step Failure", "Search Product: Xtend ", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase06");
        }
        status = homePage.addProductToCart("Xtend Smart Watch");
        if (!status) {
            logStatus("Step Failure", "Add Product: Xtend ", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase06");
        }
        status = homePage.searchForProduct("Lamp");
        if (!status) {
            logStatus("Step Failure", "Search Product: Lamp ", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase06");
        }
        status = homePage.addProductToCart("Yarine Floor Lamp");
        if (!status) {
            logStatus("Step Failure", "Add Product: Lamp ", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase06");
        }

        // update watch quantity to 2
        status = homePage.changeProductQuantityinCart("Xtend Smart Watch", 2);
        if (!status) {
            logStatus("Step Failure", "Change Product quantity: Xtend Smart Watch ", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase06");
        }

        // update table lamp quantity to 0
        status = homePage.changeProductQuantityinCart("Yarine Floor Lamp", 0);
        if (!status) {
            logStatus("Step Failure", "Change Product quantity: Yarine Floor Lamp ", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase06");
        }

        // update watch quantity again to 1
        status = homePage.changeProductQuantityinCart("Xtend Smart Watch", 1);
        if (!status) {
            logStatus("Step Failure", "Change Product quantity: Xtend Smart Watch ", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase06");
        }

        homePage.clickCheckout();
        // Check if placing order redirected to the Checkout page
        status = driver.getCurrentUrl().endsWith("/checkout");
        if (!status) {
            logStatus("Step Failure", "Get url: redirect to checkout page ", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase06");
        }

        Checkout checkoutPage = new Checkout(driver);
        checkoutPage.addNewAddress("Addr line 1 addr Line 2 addr line 3");
        checkoutPage.selectAddress("Addr line 1 addr Line 2 addr line 3");

         // Place the order
         status = checkoutPage.placeOrder();
         if (!status) {
            logStatus("Step Failure", "Place Order: Click place order ", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase06");
        }
 
         // Check if placing order redirected to the Thanks page
         status = driver.getCurrentUrl().endsWith("/thanks");
         if (!status) {
            logStatus("Step Failure", "Get url: redirect to thanks page ", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase06");
        }
 
         // Go to the home page
         homePage.navigateToHome();
 
         // Log out the user
         status = homePage.PerformLogout();
         if (!status) {
            logStatus("Step Failure", "Logout: user logout ", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase06");
        }
 
         logStatus("End TestCase", "Test Case 6 Happy Flow Test Completed : ", status ? "PASS" : "FAIL");

         takeScreenshot(driver, "EndTestcase", "Testcase06");
         return status;
    }

    /*
     * Verify that the cart contents are persisted after logout
     */
    public static Boolean TestCase07(RemoteWebDriver driver) throws InterruptedException {
        takeScreenshot(driver, "StartTestcase", "Testcase07");
        Boolean status = false;
        List<String> expectedResult = Arrays.asList("Stylecon 9 Seater RHS Sofa Set",
                "Xtend Smart Watch");

        logStatus("Start TestCase", "Test Case 7: Verify that cart contents are persisted after logout", "DONE");
        Home homePage = new Home(driver);

        Register registration = new Register(driver);

        registration.navigateToRegisterPage();

        status = registration.registerUser("testUser", "abc@123", true);
        if (!status) {
            logStatus("TestCase 7", "Test Case Failure. Happy Flow Test Failed", "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase07");
        }

        lastGeneratedUserName = registration.lastGeneratedUsername;

        Login login = new Login(driver);

        login.navigateToLoginPage();

        status = login.PerformLogin(lastGeneratedUserName, "abc@123");
        if (!status) {
            logStatus("Step Failure", "User Perform Login Failed", status ? "PASS" : "FAIL");
            logStatus("End TestCase", "Test Case 7: Happy Flow Test Failed : ", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase07");
        }

        status = homePage.searchForProduct("Stylecon");
        if (!status) {
            logStatus("Step Failure", "Search Product: Stylecon", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase07");
        }
        homePage.addProductToCart("Stylecon 9 Seater RHS Sofa Set");

        status = homePage.searchForProduct("Xtend");
        if (!status) {
            logStatus("Step Failure", "Search Product: Xtend", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase07");
        }
        homePage.addProductToCart("Xtend Smart Watch");

        homePage.PerformLogout();

        login.navigateToLoginPage();
        status = login.PerformLogin(lastGeneratedUserName, "abc@123");

        status = homePage.verifyCartContents(expectedResult);

        logStatus("End TestCase", "Test Case 7: Verify that cart contents are persisted after logout: ",
                status ? "PASS" : "FAIL");

        homePage.PerformLogout();

        takeScreenshot(driver, "EndTestcase", "Testcase07");
        return status;
    }

    public static Boolean TestCase08(RemoteWebDriver driver) throws InterruptedException {
        takeScreenshot(driver, "StartTestcase", "Testcase08");
        Boolean status;
        logStatus("Start TestCase",
                "Test Case 8: Verify that insufficient balance error is thrown when the wallet balance is not enough",
                "DONE");

        Register registration = new Register(driver);
        registration.navigateToRegisterPage();
        status = registration.registerUser("testUser", "abc@123", true);
        if (!status) {
            logStatus("Step Failure", "User Perform Registration Failed", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 8: Verify that insufficient balance error is thrown when the wallet balance is not enough: ",
                    status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase08");
            return false;
        }
        lastGeneratedUserName = registration.lastGeneratedUsername;

        Login login = new Login(driver);
        login.navigateToLoginPage();
        status = login.PerformLogin(lastGeneratedUserName, "abc@123");
        if (!status) {
            logStatus("Step Failure", "User Perform Login Failed", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 8: Verify that insufficient balance error is thrown when the wallet balance is not enough: ",
                    status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase08");
            return false;
        }

        Home homePage = new Home(driver);
        homePage.navigateToHome();
        status = homePage.searchForProduct("Stylecon");
        homePage.addProductToCart("Stylecon 9 Seater RHS Sofa Set");

        homePage.changeProductQuantityinCart("Stylecon 9 Seater RHS Sofa Set", 10);

        homePage.clickCheckout();

        Checkout checkoutPage = new Checkout(driver);
        checkoutPage.addNewAddress("Addr line 1 addr Line 2 addr line 3");
        checkoutPage.selectAddress("Addr line 1 addr Line 2 addr line 3");

        checkoutPage.placeOrder();

        status = checkoutPage.verifyInsufficientBalanceMessage();

        logStatus("End TestCase",
                "Test Case 8: Verify that insufficient balance error is thrown when the wallet balance is not enough: ",
                status ? "PASS" : "FAIL");

        takeScreenshot(driver, "EndTestcase", "Testcase08");
        return status;
    }

    public static Boolean TestCase09(RemoteWebDriver driver) throws InterruptedException {
        takeScreenshot(driver, "StartTestcase", "Testcase09");
        Boolean status = false;
        logStatus("Start TestCase",
                "Test Case 9: Verify products added to cart in one tab are reflected in new tab",
                "DONE");

        Register registration = new Register(driver);
        registration.navigateToRegisterPage();
        status = registration.registerUser("testUser", "abc@123", true);
        if (!status) {
            logStatus("Step Failure", "User Perform Registration Failed", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 9: Verify products added to cart in one tab are reflected in new tab: ",
                    status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase09");
            return false;
        }
        lastGeneratedUserName = registration.lastGeneratedUsername;

        Login login = new Login(driver);
        login.navigateToLoginPage();
        status = login.PerformLogin(lastGeneratedUserName, "abc@123");
        if (!status) {
            logStatus("Step Failure", "User Perform Login Failed", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 9: Verify products added to cart in one tab are reflected in new tab: ",
                    status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase09");
            return false;
        }

        Home homePage = new Home(driver);
        homePage.navigateToHome();
        status = homePage.searchForProduct("YONEX Smash Badminton Racquet");
        homePage.addProductToCart("YONEX Smash Badminton Racquet");


        List<String> expectedResult = Arrays.asList("YONEX Smash Badminton Racquet");

        JavascriptExecutor jscript = (JavascriptExecutor) driver;
        jscript.executeScript("window.open('https://crio-qkart-frontend-qa.vercel.app');");

        ArrayList<String> allWindowHandles = new ArrayList<String>(driver.getWindowHandles());
        driver.switchTo().window(allWindowHandles.get(1));

        status = homePage.verifyCartContents(expectedResult);

        if(!status){
            logStatus("Step Failure", "Verify cart contents failed", status ? "PASS" : "FAIL");
        }
        else{
            logStatus("Step Success", "Successfully validated contents of cart in new tab", "PASS");
        }

        status = homePage.changeProductQuantityinCart("YONEX Smash Badminton Racquet", 0);
        if (!status) {
            logStatus("Step Failure", "Change Product quantity: YONEX Smash Badminton Racquet ", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase09");
        }

        homePage.PerformLogout();
        
        
		driver.close();
        driver.switchTo().window(allWindowHandles.get(0));

        logStatus("End TestCase", "Test Case 9: Verify products added to cart in one tab are reflected in new tab: ",
                status ? "PASS" : "FAIL");
        
        takeScreenshot(driver, "EndTestcase", "Testcase09");
        return status;
    }

    public static Boolean TestCase10(RemoteWebDriver driver) throws InterruptedException {
        takeScreenshot(driver, "StartTestcase", "Testcase10");
        Boolean status = false;
        logStatus("Start TestCase",
                "Test Case 10: Verify clicking and opening Privacy Policy page",
                "DONE");

        Home homePage = new Home(driver);
        homePage.navigateToHome();

        String homePageURL = driver.getCurrentUrl();
        String homePageWindowHandle = driver.getWindowHandle();
        WebElement privacyPolicyLink = driver.findElement(By.linkText("Privacy policy"));
        privacyPolicyLink.click();
        status = driver.getCurrentUrl().equals(homePageURL);
        if(!status){
            logStatus("Step Failure", "Verify clicking Privacy policy opens in new tab failed", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase10");
        }
        ArrayList<String> allWindowHandles = new ArrayList<String>(driver.getWindowHandles());
		driver.switchTo().window(allWindowHandles.get(1));

        WebDriverWait wait = new WebDriverWait(driver, 30);
        status = wait.until(ExpectedConditions.textToBePresentInElementLocated(By.tagName("h2"), "Privacy Policy"));
        if(!status){
            logStatus("Step Failure", "Verify checking header on Privacy Policy page failed", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase10");
        }
        driver.switchTo().window(homePageWindowHandle);

        WebElement termsOfServiceLink = driver.findElement(By.linkText("Terms of Service"));
        termsOfServiceLink.click();

        status = driver.getCurrentUrl().equals(homePageURL);
        if(!status){
            logStatus("Step Failure", "Verify clicking Terms of Service opens in new tab failed", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase10");
        }
        allWindowHandles = new ArrayList<String>(driver.getWindowHandles());
		driver.switchTo().window(allWindowHandles.get(2));

        status = wait.until(ExpectedConditions.textToBePresentInElementLocated(By.tagName("h2"), "Terms of Service"));
        if(!status){
            logStatus("Step Failure", "Verify checking header on Terms of Service page failed", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase10");
        }
        driver.close();
        driver.switchTo().window(allWindowHandles.get(1)).close();
        driver.switchTo().window(homePageWindowHandle);

        logStatus("End TestCase", "Test Case 10: Verify clicking and opening Privacy Policy page: ",
                status ? "PASS" : "FAIL");
        takeScreenshot(driver, "EndTestcase", "Testcase10");
        return status;
    }

    public static Boolean TestCase11(RemoteWebDriver driver) throws InterruptedException {
        takeScreenshot(driver, "StartTestcase", "Testcase11");
        Boolean status = false;
        logStatus("Start TestCase",
                "Test Case 11: Verify clicking Contact us",
                "DONE");

        Home homePage = new Home(driver);
        homePage.navigateToHome();

        WebElement contactUsLink = driver.findElement(By.xpath("//p[text()='Contact us']"));
        contactUsLink.click();
        WebDriverWait wait = new WebDriverWait(driver, 30);
        
        WebElement nameInput = driver.findElement(By.xpath("//input[@placeholder='Name']"));
        nameInput.sendKeys("crio user");
        WebElement emailInput = driver.findElement(By.xpath("//input[@placeholder='Email']"));
        emailInput.sendKeys("criouser@gmail.com");
        WebElement messageInput = driver.findElement(By.xpath("//input[@placeholder='Message']"));
        messageInput.sendKeys("Testing the contact us page");
        WebElement contactNowBtn = driver.findElement(By.xpath("//button[text()=' Contact Now']"));
        contactNowBtn.click();

        wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//form[contains(@class, 'form-material')]")));
        status = wait.until(ExpectedConditions.invisibilityOfElementLocated(By.xpath("//form[contains(@class, 'form-material')]")));

        if(!status){
            logStatus("Step Failure", "Clicking Contact Now did not close the form", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase11");
        }
       
        logStatus("End TestCase", "Test Case 11: Verify clicking Contact us: ",
                status ? "PASS" : "FAIL");
        takeScreenshot(driver, "EndTestcase", "Testcase11");
        return status;
    }

    public static Boolean TestCase12(RemoteWebDriver driver) throws InterruptedException {
        takeScreenshot(driver, "StartTestcase", "Testcase12");
        Boolean status = false;
        logStatus("Start TestCase",
                "Test Case 12: Verify checking the advertisements",
                "DONE");

        Register registration = new Register(driver);
        registration.navigateToRegisterPage();
        status = registration.registerUser("testUser", "abc@123", true);
        if (!status) {
            logStatus("Step Failure", "User Perform Registration Failed", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 12: Verify checking the advertisements: ",
                    status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase12");
            return false;
        }
        lastGeneratedUserName = registration.lastGeneratedUsername;

        Login login = new Login(driver);
        login.navigateToLoginPage();
        status = login.PerformLogin(lastGeneratedUserName, "abc@123");
        if (!status) {
            logStatus("Step Failure", "User Perform Login Failed", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 12: Verify checking the advertisements: ",
                    status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase12");
            return false;
        }

        Home homePage = new Home(driver);
        homePage.navigateToHome();
        status = homePage.searchForProduct("YONEX Smash Badminton Racquet");
        homePage.addProductToCart("YONEX Smash Badminton Racquet");

        homePage.clickCheckout();

        Checkout checkoutPage = new Checkout(driver);
        checkoutPage.addNewAddress("Addr line 1 addr Line 2 addr line 3");
        checkoutPage.selectAddress("Addr line 1 addr Line 2 addr line 3");

        checkoutPage.placeOrder();
        String thanksPageURL = driver.getCurrentUrl();

        List<WebElement> ads = driver.findElements(By.xpath("//iframe"));
        if(ads.size() != 3){
            status = false;
            logStatus("Step Failure", "2 ads are not present", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase12");
        }

        WebElement adFrame1 = driver.findElement(By.xpath("//iframe[1]"));
        driver.switchTo().frame(adFrame1);
        WebElement ad1ViewCartBtn = driver.findElement(By.xpath("//button[contains(@class, 'css-rfvjbl') and text()='View Cart']"));
        ad1ViewCartBtn.click();

        if(driver.getCurrentUrl().equals(thanksPageURL)){
            status = false;
            logStatus("Step Failure", "Advertisement 1 View Cart button is not clickable", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase12");
        }
        else {
            status = true;
            logStatus("Step Success", "Advertisement 1 View Cart button is clickable", status ? "PASS" : "FAIL");
        }
        
        driver.navigate().back();
        

        WebDriverWait wait = new WebDriverWait(driver, 30);

        wait.until(ExpectedConditions.frameToBeAvailableAndSwitchToIt(By.xpath("//iframe[1]")));
        
        
        WebElement ad1BuyNowBtn = driver.findElement(By.xpath("//button[contains(@class, 'css-rfvjbl') and text()='Buy Now']"));
        ad1BuyNowBtn.click();

        if(driver.getCurrentUrl().equals(thanksPageURL)){
            status = false;
            logStatus("Step Failure", "Advertisement 1 Buy now button is not clickable", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase12");
        }
        else {
            status = true;
            logStatus("Step Success", "Advertisement 1 Buy now button is clickable", status ? "PASS" : "FAIL");
        }
        
        driver.navigate().back();
        wait.until(ExpectedConditions.frameToBeAvailableAndSwitchToIt(By.xpath("//iframe[2]")));

        WebElement ad2ViewCartBtn = driver.findElement(By.xpath("//button[contains(@class, 'css-rfvjbl') and text()='View Cart']"));
        ad2ViewCartBtn.click();

        if(driver.getCurrentUrl().equals(thanksPageURL)){
            status = false;
            logStatus("Step Failure", "Advertisement 2 View Cart button is not clickable", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase12");
        }
        else {
            status = true;
            logStatus("Step Success", "Advertisement 1 View Cart button is clickable", status ? "PASS" : "FAIL");
        }
        
        driver.navigate().back();
        wait.until(ExpectedConditions.frameToBeAvailableAndSwitchToIt(By.xpath("//iframe[2]")));
        WebElement ad2BuyNowBtn = driver.findElement(By.xpath("//button[contains(@class, 'css-rfvjbl') and text()='Buy Now']"));
        ad2BuyNowBtn.click();

        if(driver.getCurrentUrl().equals(thanksPageURL)){
            status = false;
            logStatus("Step Failure", "Advertisement 2 Buy now button is not clickable", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestcaseFailure", "Testcase12");
        }
        else {
            status = true;
            logStatus("Step Success", "Advertisement 2 Buy now button is clickable", status ? "PASS" : "FAIL");
        }

        logStatus("End TestCase", "Test Case 12: Verify checking the advertisements: ",
                status ? "PASS" : "FAIL");

        driver.switchTo().parentFrame();
        homePage.PerformLogout();
        takeScreenshot(driver, "EndTestcase", "Testcase09");
        return status;
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        int totalTests = 0;
        int passedTests = 0;
        Boolean status;
        RemoteWebDriver driver = createDriver();
        // Maximize and Implicit Wait for things to initailize
        driver.manage().window().maximize();
        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);

        try {
            // Execute Test Case 1
            totalTests += 1;
            status = TestCase01(driver);
            if (status) {
                passedTests += 1;
            }

            System.out.println("");

            // // // Execute Test Case 2
            totalTests += 1;
            status = TestCase02(driver);
            if (status) {
                passedTests += 1;
            }

            System.out.println("");
            
            //Execute Test Case 3
            totalTests += 1;
            status = TestCase03(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");

            // // Execute Test Case 4
            totalTests += 1;
            status = TestCase04(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");

            // // Execute Test Case 5
            totalTests += 1;
            status = TestCase05(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");

            // // Execute Test Case 6
            totalTests += 1;
            status = TestCase06(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");

            // // Execute Test Case 7
            totalTests += 1;
            status = TestCase07(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");

            // // Execute Test Case 8
            totalTests += 1;
            status = TestCase08(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");

            // Execute Test Case 9
            totalTests += 1;
            status = TestCase09(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");

            // Execute Test Case 10
            totalTests += 1;
            status = TestCase10(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");

            // Execute Test Case 11
            totalTests += 1;
            status = TestCase11(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");

            // Execute Test Case 12
            totalTests += 1;
            status = TestCase12(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");

        } catch (Exception e) {
            throw e;
        } finally {
            // quit Chrome Driver
            driver.quit();

            System.out.println(String.format("%s out of %s test cases Passed ", Integer.toString(passedTests),
                    Integer.toString(totalTests)));
        }

    }
}